### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by glennreyes** [iansinnott/react-static-webpack-plugin#14]
According to following warnings
```
npm WARN react-static-webpack-plugin@1.2.0 requires a peer of webpack@~1.13.1 but none was installed.
npm WARN react-static-webpack-plugin@1.2.0 requires a peer of extract-text-webpack-plugin@^1.0.1 but none was installed.
```

I wonder if we could update peer deps for `webpack` and `extract-text-webpack-plugin`. I am using them at v2 without any issues.

**Comment by iansinnott** [comment]
Updated peer dependencies. I haven't had a chance to use the latest versions of extract text plugin or webpack so please let me know if you have any issues.

**Comment by glennreyes** [comment]
@iansinnott Sure! Should be fine for now 🙌

**Comment by iansinnott** [comment]
Published to npm
