### ISSUE TITLE
Templating with JSX

### ISSUE THREAD

**Issue by iansinnott** [iansinnott/react-static-webpack-plugin#3]
We currently allow customized templates via the `template` option, but it's not great because the user must use strings instead of JSX. This plugin is to help when building with React, so it would make sense to allow templating with JSX instead of string values.

**Comment by petebrowne** [comment]
Along the same lines, it'd be nice to add support for using something like [react-document-meta](https://www.npmjs.com/package/react-document-meta) for the title/meta tags, instead of setting properties on the route object.

**Comment by iansinnott** [comment]
Oooh nice, thanks for the suggestion @petebrowne. I'll check out that lib next time I work on this issue

**Comment by iansinnott** [comment]
**Note to self:** Might be able to accomplish JSX templating using babel-core directly for string transpilation: https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#babel-core

**Comment by scherler** [comment]
You could use ejs. Have a look at https://github.com/scherler/react-es6-webpack-boilerplate/blob/master/webpack.config.production.js where I am using the static-render-webpack-plugin (from there you can see how they doing it).

**Comment by iansinnott** [comment]
Thanks for the suggestion @scherler. EJS would certainly be a more rich templating experience than simple string interpolation. The reasoning for using JSX is that since JSX already provides a rich tempalting experience and it will already be known by most people using this plugin.

**Comment by iansinnott** [comment]
Added support for this in v1 (diff bae92d1).

**Comment by petebrowne** [comment]
I like the changes a lot, thanks for the update!
