### ISSUE TITLE
Inject scripts with webpack

### ISSUE THREAD

**Issue by jonathanasquier** [iansinnott/react-static-webpack-plugin#30]
Hi, is there a way to inject the created scripts in the template the same way html-webpack-plugin does with the chunks key, rather than having `<script src='/app.js' />`?

Thanks!

**Comment by iansinnott** [comment]
Hey @jonathanasquier, i've used HTML webpack plugin before but never for the feature you're describing. can you give me a bit more info on what you mean?

**Comment by iansinnott** [comment]
I'm not sure if it pertains to this issue, but support for the `[hash]` parameter was added a while back in #6.

**Comment by jonathanasquier** [comment]
Interesting parts in the webpack config
```
module.exports = {
  entry: {
    app: './app.js',
    vendor: ['moment'],
  },
  output: {
    path: path.join(__dirname, 'build'),
    publicPath: '/',
    filename: '[hash].[name].js',
  },
    new webpack.optimize.CommonsChunkPlugin('vendor', '[hash].vendor.js', Infinity),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      chunks: ['app', 'vendor'],
      template: './index.pug',
    })
  ],
};
```
output
```
<!DOCTYPE js>
<html class="no-js">
<head>
    ...
</head>
<body>
    <h1>The index</h1>
    <script type="text/javascript" src="/6eba1b490e70e74590c9.vendor.js"></script>
    <script type="text/javascript" src="/6eba1b490e70e74590c9.app.js"></script>
</body>
</html>
```

The template has no script tag at the begining

Otherwise a way to get `{scripts : [/6eba1b490e70e74590c9.vendor.js, /6eba1b490e70e74590c9.app.js]}` as props in the template function and render the scripts using jsx?

**Comment by iansinnott** [comment]
Ah, I see. There's currently no support for this but I'm sure it could be added, likely in much the same way as we add the hash: https://github.com/iansinnott/react-static-webpack-plugin/blob/master/src/index.js#L264

Or if nothing else i'm sure the html webpack plugin has the answer within its source. We might even be able to simply pass the entire `compilation` object to the template renderer.

**Comment by jonathanasquier** [comment]
Ok cool, i plan on making a static website with a page with a rich app (front end router with lazy loading an stuff) so i need full control on which script i load on each page (otherwise i would get react errors on the static pages because no #root would be found and stuff) anyway i'll check on my side (webpack still a bit obscure for me) if you plan on adding this feel free to mention me :D i'm using your boilerplate, simply awesome :)

**Comment by iansinnott** [comment]
Sounds great. I would certainly like to further optimize this and adding chunk support would help in that regard. I've sort of been waiting for Webpack 2 to land in a stable form before trying to do any new dev, but hopefully that will be released this year.
