### ISSUE TITLE
Issues when passing reduxStore key

### ISSUE THREAD

**Issue by jonathanasquier** [iansinnott/react-static-webpack-plugin#33]
Hi,
I'm trying to use redux with the plugin, it works well If I dont set the reduxStore key, but I have a `window is not defined` error when setting de redux store (here in redux-localstorage)
Is this an issue with `react-static-webpack-plugin` or should testing `window` be handled by the redux-localstorage module?

Thanks!

**Comment by iansinnott** [comment]
This relates to #31. Currently it's up to you to ensure your app can be rendered in a node process without any browser specific stuff (like localStorage). In this particular case I'm not sure. It depends on where redux-localstorage is accessing `localStorage`. If there is a way to wrap your code such that it doesn't run during a static render then I would suggest going that route. I.e.

```js
if (typeof document !== 'undefined') {
  // use react-localstorage since we're in a browser
}
```

**Comment by jonathanasquier** [comment]
Ok, thanks!

**Comment by iansinnott** [comment]
@jonathanasquier as a heads up the latest version _does_ indeed mock the whole browser env using JSDOM so upgrading may address you original issue.
