### ISSUE TITLE
not checking for file existance before processing

### ISSUE THREAD

**Issue by gogocurtis** [iansinnott/react-static-webpack-plugin#36]
I threw this in before line 167 in utils.js to debug an issue with paths that I had.
   

if (err != undefined) {
        return reject(new Error("Failed to Compile:\n" + err));
      }

**Comment by iansinnott** [comment]
Thanks for the feedback @gogocurtis. I'm not sure what you mean though. I have been working to improve error reporting lately, at least in debug mode. Do you have any suggestions for how to best handle this?

**Comment by gogocurtis** [comment]
Hi Ian, I'm not super familar with the childCompiler interface.

I think the biggest win is to check to see if what "err" is and print it/reject the promis

It looks like you are checking childCompilation errors, however "err"
must be describing "pre-compile" issues.


```
childCompiler.runAsChild(function(err, entries, childCompilation) {
      // Resolve / reject the promise
      if (childCompilation.errors && childCompilation.errors.length) {
        const errorDetails = childCompilation.errors.map((err) => {
          return err.message + (err.error ? ':\n' + err.error : '');
        }).join('\n');

        reject(new Error('Child compilation failed:\n' + errorDetails));
      } else {
        let asset = compilation.assets[outputFilename];

        // See 'optimize-chunk-assets' above
        if (rawAssets[outputFilename]) {
          debug(`Using raw source for ${filepath}`);
          asset = rawAssets[outputFilename];
        }

        resolve(asset);
      }
    });
```

**Comment by iansinnott** [comment]
Ah, good call. It does seem that that error was being silently swallowed
