### ISSUE TITLE
doesn't work with webpack.optimize.UglifyJsPlugin

### ISSUE THREAD

**Issue by mqklin** [iansinnott/react-static-webpack-plugin#37]
<s>[Demo](https://github.com/mqklin/react-static-webpack-plugin-uglify-bug)</s>
[Demo](https://github.com/iansinnott/react-static-webpack-plugin/pull/39)

During bundle webpack throws: `Unhandled rejection Error: Error: Child compilation failed:
__react-static-webpack-plugin__template.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [__react-static-webpack-plugin__template.js:4156,20]
`

If I remove `UglifyJsPlugin`, it works fine... Very weird, how can I fix this?

**Comment by iansinnott** [comment]
Hm, thanks for the repro steps. I'm not sure what the issue might be, because I use the uglify plugin all the time. Maybe you need to provide a configuration object? 

Many of the examples—which are also the tests—use the uglify plugin. [Here for example](https://github.com/iansinnott/react-static-webpack-plugin/blob/6337ddedbacfb9ddc224ee4c87c9fb4662147cb9/example/extract-css/webpack.config.prod.js#L29). Maybe try using that example to reconfigure your demo?

**Comment by mqklin** [comment]
Ok, I [change your example a bit](https://github.com/iansinnott/react-static-webpack-plugin/pull/39)
The error is similar: `Unhandled rejection Error: Error: Child compilation failed:
1.__react-static-webpack-plugin__routes.js from UglifyJs
SyntaxError: Unexpected token: punc (:) [1.__react-static-webpack-plugin__routes.js:3,8]
`

**Comment by mqklin** [comment]
Ok, I [changed your example a bit](https://github.com/iansinnott/react-static-webpack-plugin/pull/39)
The error is similar: `Unhandled rejection Error: Error: Child compilation failed:
1.__react-static-webpack-plugin__routes.js from UglifyJs
SyntaxError: Unexpected token: punc (:) [1.__react-static-webpack-plugin__routes.js:3,8]
`
Works just fine without `UglifyJsPlugin`

**Comment by iansinnott** [comment]
ah, i see. I've never tried using this library with `require.ensure` so my guess is that its simply doesn't work yet. I've never used require.ensure in my projects so i'm not sure what might be causing the error.

I might need to add a note to the readme about this limitation.

**Comment by mqklin** [comment]
No, it's not just `require.ensure`. In my real project i use `react-static-webpack-plugin` and `require.ensure` without errors, but there is another limitation: i cannot use  `import` directive with `require.ensure` in one module.

Before `react-static-webpack-plugin` my code was like this:
```
import Slick from 'react-slick';
import MyModule from './MyModule';
...
render() {
  return (
    <div>
      <Slick />
      <MyModule />
    </div>
  );
}
```
Then i included `react-static-webpack-plugin` and `matchMedia` error appeared (([this issue](https://github.com/iansinnott/react-static-webpack-plugin/issues/38))). So I decided to convert `import Slick from 'react-slick'` to `require.ensure([], ...)` inside `componentDidMount`:

```
import MyModule from './MyModule';
...
state = {
  Slick: () => null,
};
componentDidMount() {
  require.ensure([], () => {
    const Slick = require('react-slick');
    this.setState({ Slick: Slick.default });
  });
}
render() {
  const { Slick } = this.state;
  return (
    <div>
      <Slick />
      <MyModule />
    </div>
  );
}
```

But then another error appeared -  `Unexpected token: punc (:)` from uglifyjs. After playing a bit I converted all `import`s  to `require.ensure`:

```
state = {
  Slick: () => null,
  MyModule: () => null,
};
componentDidMount() {
  require.ensure([], () => {
    const Slick = require('react-slick');
    const MyModule = require('./MyModule');
    this.setState({
      Slick: Slick.default,
      MyModule: MyModule.default, 
    });
  });
}
render() {
  const { Slick, MyModule } = this.state;
  return (
    <div>
      <Slick />
      <MyModule />
    </div>
  );
}
```

and now it works fine (even with uglify), like before `react-static-webpack-plugin`, but with great benefit from it (i mean filled index.html file).

But i want to my code to run without `require.ensure`, that's why i created these issues :)

So i'm sure that this is not `require.ensure` problem, i can create an example to prove it. If you want i can create a bunch of examples when this error appears. I thought this error will disappear with `webpack 2` because of [this comment](https://github.com/webpack/webpack/issues/1542#issuecomment-150505189), but it didn't :(

**Comment by mqklin** [comment]
With and without `react-static-webpack-plugin` compiled files without uglifyjs are *exactly* the same. And without `react-static-webpack-plugin` uglifyjs works without errors.
But `react-static-webpack-plugin` + uglify js throws the error `SyntaxError: Unexpected token: punc (:) [0.aabaac3cd527cccac417.js:3,8]`
`0.aabaac3cd527cccac417.js` file:
```
webpackJsonp([0],{

/***/ 476: *// <= react-static-webpack-plugin + uglifyjs fails here* 
/***/ (function(module, exports, __webpack_require__) {
...
```

**Comment by mqklin** [comment]
In the source code, in the file `utils.js` i removed this check (line 155):
```
if (childCompilation.errors && childCompilation.errors.length && false) { // I added false here
        const errorDetails = childCompilation.errors.map((err) => {
          return err.message + (err.error ? ':\n' + err.error : '');
        }).join('\n');

        reject(new Error('Child compilation failed:\n' + errorDetails));
      }
```
and it work just fine now. But i'm not going to create PR, this fix is silly. Do you have any thoughts?

**Comment by mqklin** [comment]
So now my `package.json` looks like this:
```
...
"react-static-webpack-plugin": "git+https://github.com/mqklin/react-static-webpack-plugin#fix-uglifyjs-error",
...
```
Ugly, but it works
Console output:
![1](https://cloud.githubusercontent.com/assets/9456433/22020089/372e7c76-dcd8-11e6-8650-a79e83fc4daa.png)

**Comment by ben181231** [comment]
Any update for this issue? I am still suffering this. 😢

**Comment by iansinnott** [comment]
@ben181231 are you using `require.ensure`?

**Comment by ben181231** [comment]
> @ben181231 are you using require.ensure?

@iansinnott Thanks for the response. I finally found out that there is another issue causing that. 😅

**Comment by iansinnott** [comment]
Great to hear @ben181231! Could you share your solution? It might help someone else who runs into similar issues.

**Comment by ben181231** [comment]
The build log is like [this](https://travis-ci.org/SkygearIO/skygear-doc/builds/210027490#L300). But finally I found that I forgot to add one directory to the `include` list of the `babel-loader`. (That may be not related to the plugin)
