### ISSUE TITLE
error in extract-css example

### ISSUE THREAD

**Issue by mqklin** [iansinnott/react-static-webpack-plugin#40]
Steps:
1. git clone this repo
2. `npm i && npm run build` inside root folder
3. `npm i && npm run build` inside `examples/extract-css` folder
4. `cd public && http-server -a localhost -p 3001`
5. go to `localhost:3001`
6. open console
![image](https://cloud.githubusercontent.com/assets/9456433/21957561/adabb4a6-daba-11e6-9080-cba9d02d5d2a.png)

**Comment by mqklin** [comment]
PR: https://github.com/iansinnott/react-static-webpack-plugin/pull/41

**Comment by iansinnott** [comment]
Thanks for the PR!
