### ISSUE TITLE
Cannot Run Webpack 2 Example

### ISSUE THREAD

**Issue by arnoldsandoval** [iansinnott/react-static-webpack-plugin#68]
When trying to run the prokect in example/webpack-2 I am getting the following error: 

`` 94% asset optimizationError: Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr``

Steps to Reproduce:
1. Pull repository
2. `cd examples/webpack-2`
3. `yarn install`
4. `./node_modules/webpack/bin/webpack.js --env=prod --config=webpack.config.prod.js --progress --profile --colors`

Fairly minor in the grand scheme of things, but I thought I would report it just in case it was uncaught.

Thanks for your work on this!

**Comment by iansinnott** [comment]
Hey, thanks for bringing this up. Do you know what the issue was?

**Comment by arnoldsandoval** [comment]
@iansinnott sorry I didnt see this notification sooner. I do not recall, I'm happy to attempt to reproduce if you think it will help!

**Comment by iansinnott** [comment]
OK, no worries @arnoldsandoval. I was just wondering in case someone else ran into the same issue but no need to go to the trouble of repro-ing
