### ISSUE TITLE
Page reload issues

### ISSUE THREAD

**Issue by BillyFigueroa** [iansinnott/react-static-webpack-plugin#70]
My react static website is acting like a SPA. When I go to one of the routes, if I reload on that route, it gives me an error. Are server wrewrites necessary for this to work?

It is all working fine locally and I even tested with a PHP server before pushing to production and reloading works in both cases but when I push to production it does not reload

Also if I use a link which takes me to another website and I click the back button, the same thing happens...error. Page doesn't load if it is not the home page I am going back to

Also I am using https://serverpilot.io/ to set up my website so I cannot create my own conf file. I can only modify what they have created by sort of "overriding" the auto-generated file they create

**Comment by BillyFigueroa** [comment]
I found a way to do this using apache. Serverpilot uses both nginx and apache. One as a proxy etc so I can still use .htaccess files

I added this in the .htaccess file

```bash
<IfModule mod_rewrite.c>

IndexIgnore *

RewriteEngine On

RewriteBase /
#================================#
# Remove trailing slashes
#================================#
RewriteRule ^(.*)/$ $1 [R,L]

#================================#
# Handle link reloads
#================================#
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]

</IfModule>
```

For some reason I kept running into issues with modifying conf files on the server. Maybe someone else has done this on serverpilot auto-generated conf files, but for now this works :/

**Comment by iansinnott** [comment]
Hey @BillyFigueroa thanks for this. I don't have much experience with Apache and I've never used serverpilot but thanks for posting your troubleshooting here. Hopefully this issue can help anyone else who runs into a similar issue

**Comment by BillyFigueroa** [comment]
Yea, the script you provide probably works for someone who has created their own conf files. In my case I couldn't get it to work, even when adding the nginx lines for removing the slashes and reloading pages the try_files I think it's called

Anyhow, hopefully it does help someone. It was giving me quite a headache lol
